name: Hacks
version: 0.8.0-BETA
api: [5.0.0]
main: Inaayat\Hacks\Main
author: Inaayat
description: Server-side hacks
website: https://github.com/Inaay/Hacks

permissions:
  hacks.command:
    default: op
    description: Server-side hacks/cheats